enum ErrorType {
  VALIDATION,
  NOT_FOUND,
  CREATION_ERROR,
  UPDATE_ERROR,
  NOT_AUTHORIZED,
  INTERNAL_SERVER_ERROR,
  UPDATE_ERRROR,
  DELETE_ERROR,
  LOGIN_ERROR,
  REGISTRATION_ERROR,
  PASSWORD_VALIDATION_ERROR,
}

export default ErrorType;
